// Turn a Markdown result into a PDF (with wrapped tables), Excel, or Word (.docx).
import PDFDocument from 'pdfkit'
import ExcelJS from 'exceljs'
import { Document, Packer, Paragraph, HeadingLevel, TextRun, Table, TableRow, TableCell, WidthType } from 'docx'

const inline = (s) => s.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1').replace(/`(.*?)`/g, '$1')
const tableRows = (lines) => lines
  .map(l => l.trim().replace(/^\|/, '').replace(/\|$/, '').split('|').map(c => inline(c.trim())))
  .filter(r => !r.every(c => /^:?-+:?$/.test(c)))

// ---------------- PDF ----------------
export function renderPDF(title, md) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' })
    const chunks = []
    doc.on('data', c => chunks.push(c)); doc.on('end', () => resolve(Buffer.concat(chunks))); doc.on('error', reject)
    const LEFT = 50

    doc.font('Helvetica-Bold').fontSize(20).fillColor('#111').text(title, LEFT, doc.y)
    doc.moveDown(0.2).font('Helvetica').fontSize(9).fillColor('#888').text(`Generated by Atlas · ${new Date().toLocaleString()}`)
    doc.fillColor('#111').moveDown(0.8)

    const lines = md.split('\n')
    for (let i = 0; i < lines.length; i++) {
      const t = lines[i].trim()
      if (!t) { doc.moveDown(0.4); continue }
      if (t.startsWith('|') && t.includes('|')) {
        const tbl = []
        while (i < lines.length && lines[i].trim().startsWith('|')) { tbl.push(lines[i]); i++ }
        i--
        drawTable(doc, tableRows(tbl), LEFT); continue
      }
      doc.x = LEFT
      if (/^#{1,6}\s/.test(t)) {
        const lvl = t.match(/^#+/)[0].length
        doc.moveDown(0.3).font('Helvetica-Bold').fontSize(lvl <= 1 ? 16 : lvl === 2 ? 13 : 12).fillColor('#111').text(inline(t.replace(/^#+\s/, '')), LEFT)
        doc.font('Helvetica').fontSize(11).moveDown(0.15); continue
      }
      if (/^[-*]\s/.test(t)) { doc.font('Helvetica').fontSize(11).fillColor('#222').text('•  ' + inline(t.replace(/^[-*]\s/, '')), LEFT + 12, doc.y); continue }
      if (/^\d+\.\s/.test(t)) { doc.font('Helvetica').fontSize(11).fillColor('#222').text(inline(t), LEFT + 12, doc.y); continue }
      if (/^---+$/.test(t)) { const y = doc.y + 2; doc.moveTo(LEFT, y).lineTo(545, y).strokeColor('#ddd').lineWidth(1).stroke().strokeColor('#111'); doc.moveDown(0.5); continue }
      doc.font('Helvetica').fontSize(11).fillColor('#222').text(inline(t), LEFT, doc.y); doc.moveDown(0.15)
    }
    doc.end()
  })
}

function drawTable(doc, rows, LEFT) {
  if (!rows.length) return
  const cols = Math.max(...rows.map(r => r.length))
  const tableW = 495, colW = tableW / cols, padX = 5, padY = 5
  doc.fontSize(9)
  rows.forEach((row, ri) => {
    doc.font(ri === 0 ? 'Helvetica-Bold' : 'Helvetica')
    let rowH = 0
    for (let c = 0; c < cols; c++) {
      const h = doc.heightOfString(row[c] || '', { width: colW - 2 * padX })
      if (h > rowH) rowH = h
    }
    rowH += 2 * padY
    if (doc.y + rowH > doc.page.height - 50) doc.addPage()
    const y = doc.y
    for (let c = 0; c < cols; c++) {
      const x = LEFT + c * colW
      if (ri === 0) doc.rect(x, y, colW, rowH).fill('#eef2f9')
      doc.rect(x, y, colW, rowH).strokeColor('#ccc').lineWidth(0.5).stroke()
      doc.fillColor('#111').font(ri === 0 ? 'Helvetica-Bold' : 'Helvetica')
        .text(row[c] || '', x + padX, y + padY, { width: colW - 2 * padX })
    }
    doc.y = y + rowH
  })
  doc.x = LEFT
  doc.moveDown(0.5)
}

// ---------------- Excel ----------------
export async function renderExcel(title, md) {
  const wb = new ExcelJS.Workbook()
  const ws = wb.addWorksheet('Report')
  const tblLines = md.split('\n').filter(l => l.trim().startsWith('|'))
  if (tblLines.length) {
    tableRows(tblLines).forEach((r, i) => { const row = ws.addRow(r); if (i === 0) row.font = { bold: true } })
  } else {
    const r = ws.addRow([title]); r.font = { bold: true, size: 14 }
    md.split('\n').forEach(l => l.trim() && ws.addRow([inline(l.replace(/^#+\s/, ''))]))
  }
  ws.columns.forEach(c => { c.width = 32 })
  return Buffer.from(await wb.xlsx.writeBuffer())
}

// ---------------- Word (.docx) ----------------
export async function renderDocx(title, md) {
  const children = [new Paragraph({ text: title, heading: HeadingLevel.TITLE })]
  const lines = md.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const t = lines[i].trim()
    if (!t) continue
    if (t.startsWith('|') && t.includes('|')) {
      const tbl = []
      while (i < lines.length && lines[i].trim().startsWith('|')) { tbl.push(lines[i]); i++ }
      i--
      const rows = tableRows(tbl)
      const cols = Math.max(...rows.map(r => r.length))
      children.push(new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: rows.map((r, ri) => new TableRow({
          children: Array.from({ length: cols }, (_, c) => new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: r[c] || '', bold: ri === 0 })] })],
          })),
        })),
      }))
      children.push(new Paragraph({ text: '' }))
      continue
    }
    if (/^#{1,6}\s/.test(t)) {
      const lvl = t.match(/^#+/)[0].length
      children.push(new Paragraph({ text: inline(t.replace(/^#+\s/, '')), heading: lvl <= 1 ? HeadingLevel.HEADING_1 : lvl === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3 }))
    } else if (/^[-*]\s/.test(t)) {
      children.push(new Paragraph({ text: inline(t.replace(/^[-*]\s/, '')), bullet: { level: 0 } }))
    } else {
      children.push(new Paragraph({ text: inline(t) }))
    }
  }
  const doc = new Document({ sections: [{ children }] })
  return await Packer.toBuffer(doc)
}
